name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: huyluu2002/devops-lab:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Restart Kubernetes deployment
        run: |
          export KUBECONFIG=/home/lth/.kube/config
          kubectl get nodes
          kubectl rollout restart deployment devops-lab
          kubectl rollout status deployment devops-lab
